#!/usr/bin/env python

import sys
import os
from link import lnk
from optparse import OptionParser

parser = OptionParser()

parser.add_option("-i", "--install", dest="install", 
                  help="install this file in the wrappers directory")

parser.add_option("-r", "--install_git", dest="install_git",
                  help="install from git location into wrappers file")

parser.add_option("-g", "--global_install", dest="global_install",
                  help="If set to global it will be installed into link in site packages")


def get_from_git(location):
    pass


def main():
    """
    Take in user input.  Start up the vlnk shell
    """
    (options, args) = parser.parse_args()

    install_file = options.install
    install_git = options.install_git
    install_global = options.global_install

    if install_file:
        lnk.install_plugin(install_file, install_global)
        
    if install_git:
        file = get_from_git(install_git, install_global)
        install_wrapper(file)


if __name__ == '__main__':
    main()

