#!/usr/bin/env python

import sys
import os
from link import lnk
from optparse import OptionParser
from subprocess import Popen

parser = OptionParser()

parser.add_option("-i", "--install", dest="install", 
                  help="install this file in the wrappers directory")

parser.add_option("-r", "--install_git", dest="install_git",
                  help="install from git location into wrappers file")

parser.add_option("-g", "--global_install",
                  dest="global_install",action="store_true",  default=False,
                  help="If set to global it will be installed into link in site packages")


def get_from_git(location):
    """
    Run git and put the data in the plugins tmp directory.  
    From there install it
    """
    tmp = lnk.plugins_directory()
    name = location.split("/")[-1].split('.')[0]
    clone_to = '%s/%s' % (tmp, name)
    print "getting the plugin from git and placing in %s" % clone_to
    p = Popen("git clone %s %s" % (location ,clone_to), shell=True)
    p.wait()
    print "done getting file"
    return clone_to

def main():
    """
    Take in user input.  Start up the vlnk shell
    """
    (options, args) = parser.parse_args()

    install_file = options.install
    install_git = options.install_git
    install_global = options.global_install

    if install_file:
        lnk.install_plugin(install_file, install_global)
    elif install_git:
        install_file = get_from_git(install_git)
        #lnk.install_plugin(install_file, install_global)

if __name__ == '__main__':
    main()

